#!/usr/bin/python

import sys
import xml.dom.minidom as dom

usage = """set_xml_attr <file_to_edit> <element> <attribute> <value>"""

if len(sys.argv) < 4:
    print usage
    sys.exit(1)
    
xmlfile=sys.argv[1]
element=sys.argv[2]
attr=sys.argv[3]
value=sys.argv[4]

xml = dom.parse(xmlfile)
element = xml.getElementsByTagName(element)[0]
element.setAttribute(attr, value)

open(xmlfile, 'w').write(xml.toxml())
