#!/bin/sh
# Mount Drag and Drog shared folder,
# and start VBoxClient DnD service
. /etc/sysconfig/ufo/vboxclient

[ -z "$SUDO_UID" ] && USER_UID=`id -u $USER` || USER_UID=$SUDO_UID

export VBOX_DND_SF_PATH=$VBOX_DND_SF_PATH

[ -d "$VBOX_DND_SF_PATH" ] || mkdir "$VBOX_DND_SF_PATH"

echo "sudo mount.vboxsf DnD \"$VBOX_DND_SF_PATH\" -o \"uid=$USER_UID,rw\""
mountvboxsf DnD "$VBOX_DND_SF_PATH" -o "uid=$USER_UID,rw"

VBoxClient -d --dnd > $VBOX_DND_SF_PATH/vbox-dnd.log
