#!/bin/sh

[ ! -d /media/UFO ] && mkdir /media/UFO
runlevel=`runlevel | cut -d " " -f 2`
if [ "$runlevel" = 4 ]; then
    mount.vboxsf PUBLIC /media/UFO -o uid=$USERHELPER_UID,rw,dmode=755,fmode=755
else
    . /etc/sysconfig/ufo/uuids
    fat=`findfs UUID=$UFO`
    mount $fat /media/UFO
fi

user=`basename $HOME`
if [ "$user" = "guest" ]; then
    for folder in Bureau Documents Images Modèles Musique Téléchargements Vidéos
    do
        mount --bind /media/UFO/Public/$folder $HOME/$folder
    done
else
    mount --bind /media/UFO/Public $HOME/Public
fi
