#!/bin/sh

user=`basename $HOME`
desktop=$(su $user xdg-user-dir DESKTOP)

[ ! -d /media/UFO ] && mkdir /media/UFO
runlevel=`runlevel | cut -d " " -f 2`
if [ "$runlevel" = 4 ]; then
    mount.vboxsf UFO /media/UFO -o uid=$USERHELPER_UID,rw,dmode=755,fmode=755
else
    . /etc/sysconfig/ufo/uuids
    fat=`findfs UUID=$UFO`
    mount $fat /media/UFO
fi

if [ "$user" = "guest" ]; then
    for folder in Bureau Documents Images Modèles Musique Téléchargements Vidéos
    do
        mount --bind /media/UFO/Public/$folder $HOME/$folder
    done
else
    mount --bind /media/UFO/Public $HOME/Public
    cat > $desktop/public.desktop <<EOF
#!/usr/bin/env xdg-open

[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Link
Name=Public
Name[fr_FR]=Public
Comment=My public files
Comment[fr_FR]=Mes fichiers publics
URL=/media/UFO/Public
Icon=gdu-encrypted-unlock
EOF
    chown $user:$user $desktop/public.desktop
fi
