#!/bin/sh

TEXTDOMAIN=vlaunch-guest
[ "$USER" = "user" ] && notify-send --icon=/usr/share/icons/UFO/48x48/places/firstboot.png $"You are currently logged in guest mode. Please consider clicking on the 'Setup my key' icon to get access to services like synchronization of your files, encryption, and more"
