#!/bin/sh

TEXTDOMAIN=vlaunch-guest

start_gnome() {
	echo "start-gnome"
	sed "s?PREFERRED=[^$]*?PREFERRED=/usr/bin/gnome-session?" /etc/sysconfig/desktop > /tmp/switch
	cat /tmp/switch > /etc/sysconfig/desktop
	rm /tmp/switch
	export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
	gconftool-2 --set -t bool /apps/nautilus/preferences/show_desktop true
	gconftool-2 --set -t string /desktop/gnome/applications/browser/exec firefox
	gconftool-2 --set -t string /desktop/gnome/url-handlers/http/command firefox
	gconftool-2 --set -t string /desktop/gnome/url-handlers/https/command firefox
	gconftool-2 --set -t string /desktop/gnome/url-handlers/about/command firefox
	gconftool-2 --set -t string /apps/panel/applications/browser/exec firefox
	gconftool-2 --set -t string /apps/panel/url-handlers/http/command firefox
	gconftool-2 --set -t string /apps/panel/url-handlers/https/command firefox
	gconftool-2 --set -t string /apps/panel/url-handlers/about/command firefox
	gconftool-2 --set -t string /desktop/gnome/background/picture_filename /usr/share/backgrounds/UFO/default/standard/ufo.png
	gconftool-2 --set -t string /apps/panel/background/picture_filename /usr/share/backgrounds/UFO/default/standard/ufo.png
	gconftool-2 --set -t string /desktop/gnome/interface/gtk_theme UFO
	gconftool-2 --set -t string /desktop/gnome/interface/icon_theme UFO
	gconftool-2 --set -t string /apps/metacity/general/theme UFO
	gconftool-2 --set -t string /apps/panel/general/theme UFO
	gconftool-2 --set -t string /apps/panel/interface/gtk_theme UFO
	gconftool-2 --set -t string /apps/panel/interface/icon_theme UFO
}

start_bloom() {
	echo "start-bloom"
	sed "s?PREFERRED=[^$]*?PREFERRED=/usr/bin/startbloom?" /etc/sysconfig/desktop > /tmp/switch
	cat /tmp/switch > /etc/sysconfig/desktop
	rm /tmp/switch
	export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
	gconftool-2 --set -t bool /apps/nautilus/preferences/show_desktop false
	gconftool-2 --set -t string /desktop/gnome/applications/browser/exec panel-web-helper
	gconftool-2 --set -t string /desktop/gnome/url-handlers/http/command panel-web-helper
	gconftool-2 --set -t string /desktop/gnome/url-handlers/https/command panel-web-helper
	gconftool-2 --set -t string /desktop/gnome/url-handlers/about/command panel-web-helper
	gconftool-2 --set -t string /apps/panel/applications/browser/exec panel-web-helper
	gconftool-2 --set -t string /apps/panel/url-handlers/http/command panel-web-helper
	gconftool-2 --set -t string /apps/panel/url-handlers/https/command panel-web-helper
	gconftool-2 --set -t string /apps/panel/url-handlers/about/command panel-web-helper
	gconftool-2 --set -t string /desktop/gnome/background/picture_filename /usr/share/backgrounds/UFO/default/standard/bloom.png
	gconftool-2 --set -t string /apps/panel/background/picture_filename /usr/share/backgrounds/UFO/default/standard/bloom.png
	gconftool-2 --set -t string /desktop/gnome/interface/gtk_theme Bloom
	gconftool-2 --set -t string /desktop/gnome/interface/icon_theme Bloom
	gconftool-2 --set -t string /apps/metacity/general/theme Bloom
	gconftool-2 --set -t string /apps/panel/general/theme Bloom
	gconftool-2 --set -t string /apps/panel/interface/gtk_theme Bloom
	gconftool-2 --set -t string /apps/panel/interface/icon_theme Bloom
}

set_gui() {
	case "$1" in
		gnome)
			start_gnome
			;;
		bloom)
			start_bloom
			;;
	esac
}

set_gui `vbox-get-property /UFO/GUI`

