#!/bin/sh

while [ 1 ]; do
    public=`df -P | grep /media/UFO | awk '{ print $5 }' | tr -d "%"`
    root=`df -P | head -n 2 | tail -n 1 | awk '{ print $5 }' | tr -d "%"`
    home=`df -P | grep /home/$USER | awk '{ print $5 }' | tr -d "%"`
    [ -n "$public" ] && [[ $public =~ ^-?[0-9]+$ ]] && vbox-set-property /UFO/DiskSpace/public $public
    [ -n "$root" ] && [[ $root =~ ^-?[0-9]+$ ]] && vbox-set-property /UFO/DiskSpace/root $root
    [ -n "$home" ] && [[ $home =~ ^-?[0-9]+$ ]] && vbox-set-property /UFO/DiskSpace/user $home
    sleep 30
done
