#!/bin/sh

dbus-send --system --dest=org.agorabox.vbox --print-reply --type=method_call /GuestProperty org.agorabox.vbox.GuestProperty.GetProperty string:$1 | while read line;
do
    read value
    echo $(echo $value | tr -d '\"' | cut -d " " -f 2)
done

exit $?

